---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wqc.
--- DateTime: 2025/3/25 13:59
---

local ScoreBossResultPanel = class("ScoreBossResultPanel", BasePanel)

ScoreBossResultPanel._bAddToBackHistory = false

ScoreBossResultPanel._tbDefine = {
    {sPrefabPath = "Play_ScoreBoss/ScoreBossResultPanel.prefab", sCtrlName = "Game.UI.ScoreBoss.ScoreBossResultCtrl"}
}

function ScoreBossResultPanel:Awake()
end
function ScoreBossResultPanel:OnEnable()
end
function ScoreBossResultPanel:OnDisable()
end
function ScoreBossResultPanel:OnDestroy()
end

return ScoreBossResultPanel