---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wqc.
--- DateTime: 2025/3/14 10:02
---
local ScoreBossEditor = class("ScoreBossEditor")
local mapEventConfig = {
    LoadLevelRefresh = "OnEvent_LoadLevelRefresh",
    [EventId.AbandonBattle] = "OnEvent_AbandonBattle",
    AdventureModuleEnter = "OnEvent_AdventureModuleEnter",
    TestBedNoteChange = "OnEvent_TestBedNoteChange",
    BossRush_Spawn_Id = "OnEvent_BossRushSpawnId",
    ScoreBoss_BehaviorScore = "OnEvent_ControlScore",
}

function ScoreBossEditor:Init(parent,nLevelId,tbChar, tbDisc, tbNote)
    self.parent = parent
    self.tbCharId = tbChar
    self.mapActorInfo = {}
    self.tbDisc = tbDisc
    self.tbNote = tbNote

    self.BossId = 0
    self.BossMaxHp = 0
    self.BossCurLvMinHp = -1
    self.BossCurLvTotalChangeHp = 0
    self.BattleLv = 1

    local leveData = ConfigTable.GetData("ScoreBossLevel", nLevelId)
    if leveData == nil then
        printError("ScoreBossLevel 表不存在 id ==== " .. nLevelId)
        return
    end
    local getControlData = ConfigTable.GetData("ScoreBossGetControl", leveData.NonDamageScoreGet)
    if getControlData == nil then
        printError("ScoreBossGetControl 表不存在 id ==== " .. leveData.NonDamageScoreGet)
        return
    end
    self.totalControlScore = 0
    self.OnceControlScore = getControlData.OnceScore
    self.MaxControlScore = getControlData.MaxLimit
    self.ScoreBossBehavior = getControlData.ScoreBossBehavior
    self.ScoreGetSwitchGroupId = leveData.ScoreGetSwitchGroup
    self.SwitchRate = 300
    local getSwitchData = ConfigTable.GetData("ScoreGetSwitch", self.ScoreGetSwitchGroupId * 1000 + 1)
    if getSwitchData ~= nil then
        self.SwitchRate = getSwitchData.SwitchRate
    end

    CS.AdventureModuleHelper.EnterScoreBossFloor(nLevelId,self.tbCharId)
    NovaAPI.EnterModule("AdventureModuleScene", true)
end

function ScoreBossEditor:OnEvent_LoadLevelRefresh()
    self:ChangeNote()
    self:ResetNoteInfo()
end

function ScoreBossEditor:OnEvent_AbandonBattle()
    --self:OnEvent_LevelResult(false,0)
end

function ScoreBossEditor:OnEvent_BossRushSpawnId(bossId)
    self.BossId = bossId
    EventManager.AddEntityEvent("HpChanged", self.BossId, self, self.OnEvent_HpChanged)
    EventManager.AddEntityEvent("BossRushMonsterLevelChanged", self.BossId, self, self.OnEvent_BossRushMonsterLevelChanged)
    EventManager.AddEntityEvent("BossRushMonsterBattleAttrChanged", self.BossId, self, self.OnEvent_BossRushMonsterBattleAttrChanged)
end

function ScoreBossEditor:OnEvent_HpChanged(hp, hpMax)
    if self.isDontChangeHp then
        return
    end
    self.BossMaxHp = hpMax
    if self.BossCurLvMinHp == -1 then
        self.BossCurLvMinHp = hp
        --self.BossCurLvTotalChangeHp = self.BossCurLvTotalChangeHp + (hpMax - hp)
        self.parent:DamageToScore(hpMax - hp,self.SwitchRate,self.BattleLv)
    end

    if self.BossCurLvMinHp > hp then
        --self.BossCurLvTotalChangeHp = self.BossCurLvTotalChangeHp + (self.BossCurLvMinHp - hp)
        self.BossCurLvMinHp = hp
        self.parent:DamageToScore(hpMax - hp,self.SwitchRate,self.BattleLv)
    end
end

function ScoreBossEditor:OnEvent_BossRushMonsterLevelChanged(oldLevel, battleLevel)
    self.isDontChangeHp = true
    self.BossCurLvTotalChangeHp = self.BossCurLvTotalChangeHp + self.BossCurLvMinHp
    self.BossCurLvMinHp = -1
    self.BattleLv = battleLevel
    --发送积分
    self.parent:DamageToScore(self.BossMaxHp,self.SwitchRate,self.BattleLv)
    if battleLevel <= 100 then
        local getSwitchData = ConfigTable.GetData("ScoreGetSwitch", self.ScoreGetSwitchGroupId * 1000 + battleLevel)
        if getSwitchData ~= nil then
            self.SwitchRate = getSwitchData.SwitchRate
        end
    end
    self.parent:HPLevelChanged()
end

function ScoreBossEditor:OnEvent_BossRushMonsterBattleAttrChanged()
    self.isDontChangeHp = false
end

function ScoreBossEditor:OnEvent_ControlScore(Id,nBehavior)
    --printError(self.BossId .. "  " .. Id .. "  " .. nBehavior .. "   " .. self.ScoreBossBehavior )
    if self.BossId == Id  and nBehavior == self.ScoreBossBehavior then
        --printError(self.totalControlScore .. "  " .. self.MaxControlScore .. "  " .. nBehavior .. "   " .. self.ScoreBossBehavior )
        if self.totalControlScore < self.MaxControlScore then
            self.totalControlScore = self.totalControlScore + self.OnceControlScore
            self.parent:BehaviorToScore(self.totalControlScore)
        end
    end
end

function ScoreBossEditor:OnEvent_AdventureModuleEnter()
    EventManager.Hit(EventId.OpenPanel, PanelId.ScoreBossBattlePanel,self.tbCharId)
    for idx, nCharId in ipairs(self.tbCharId) do
        local stActorInfo,nHeartStoneLevel= self:CalCharFixedEffect(nCharId,idx == 1)
        safe_call_cs_func(CS.AdventureModuleHelper.SetActorAttribute,nCharId,stActorInfo)
    end
    self:SetTheme()
    self:ResetDiscInfo()
    --self:SetCharFixedAttribute()
end

function ScoreBossEditor:SetCharFixedAttribute()
    for nCharId,mapInfo in pairs(self.mapActorInfo) do
        safe_call_cs_func(CS.AdventureModuleHelper.SetActorAttribute,nCharId,mapInfo.stActorInfo)
    end
end

function ScoreBossEditor:CalCharFixedEffect(nCharId,bMainChar)
    local stActorInfo = CS.Lua2CSharpInfo_CharAttribute()
    local nHeartStoneLevel = PlayerData.Char:CalCharacterAttrBattle(nCharId,stActorInfo,bMainChar,self.tbDisc)
    return stActorInfo,nHeartStoneLevel
end
function ScoreBossEditor:SetTheme()
    safe_call_cs_func(CS.AdventureModuleHelper.SetRglTheme,self.tbTheme)
end

function ScoreBossEditor:ResetDiscInfo()
    local tbDiscInfo = {}
    for k, nDiscId in ipairs(self.tbDisc) do
        if k <= 3 then
            local mapDiscData = PlayerData.Disc:GetDiscById(nDiscId)
            if mapDiscData and mapDiscData.sName then
                local discInfo = mapDiscData:GetDiscInfo(self.tbNote)
                table.insert(tbDiscInfo, discInfo)
            else
                printError("星盘数据有误id:" .. nDiscId)
            end
        end
    end
    safe_call_cs_func(CS.AdventureModuleHelper.SetDiscInfo,tbDiscInfo)
end

function ScoreBossEditor:ResetNoteInfo()
    local tbNoteInfo = {}
    for i, v in pairs(self.tbNote) do
        local noteInfo = CS.Lua2CSharpInfo_NoteInfo()
        noteInfo.noteId = i
        noteInfo.noteCount = v
        table.insert(tbNoteInfo, noteInfo)
    end
    safe_call_cs_func(CS.AdventureModuleHelper.SetNoteInfo, tbNoteInfo)
end

function ScoreBossEditor:ChangeNote()
    if not self.mapDiscEft then
        self.mapDiscEft = {}
    end
    for k, nDiscId in ipairs(self.tbDisc) do
        if k <= 3 then
            local mapDiscData = PlayerData.Disc:GetDiscById(nDiscId)
            if mapDiscData and mapDiscData.sName then
                if self.mapDiscEft[nDiscId] == nil then
                    self.mapDiscEft[nDiscId] = {}
                else
                    --移除老效果
                    for _, tbEft in pairs(self.mapDiscEft[nDiscId]) do
                        for _, tbEftData in ipairs(tbEft) do
                            UTILS.RemoveEffect(tbEftData[1],tbEftData[2])
                        end
                    end
                    self.mapDiscEft[nDiscId] = {}
                end
                --添加新效果
                local tbDiscEft = mapDiscData:GetSkillEffect(self.tbNote)
                for _, mapEft in ipairs(tbDiscEft) do
                    if self.mapDiscEft[nDiscId][mapEft[1]] == nil then
                        self.mapDiscEft[nDiscId][mapEft[1]] = {}
                        for _, nCharId in ipairs(self.tbChar) do
                            local nEftUid = UTILS.AddEffect(nCharId,mapEft[1],mapEft[2],0)
                            table.insert(self.mapDiscEft[nDiscId][mapEft[1]],{nEftUid,nCharId})
                        end
                    end
                end
            else
                printError("星盘数据有误id:" .. nDiscId)
            end
        end
    end
end

function ScoreBossEditor:OnEvent_TestBedNoteChange(noteList)
    if noteList then
        self.tbNote = {}
        for i = 0, noteList.Count - 1 do
            self.tbNote[noteList[i].Id] = noteList[i].count
        end
        self:ResetNoteInfo()
        self:ResetDiscInfo()
        self:ChangeNote()
    end
end

function ScoreBossEditor:BindEvent()
    if type(mapEventConfig) ~= "table" then
        return
    end
    for nEventId, sCallbackName in pairs(mapEventConfig) do
        local callback = self[sCallbackName]
        if type(callback) == "function" then
            EventManager.Add(nEventId, self, callback)
        end
    end
end
function ScoreBossEditor:UnBindEvent()
    if type(mapEventConfig) ~= "table" then
        return
    end
    for nEventId, sCallbackName in pairs(mapEventConfig) do
        local callback = self[sCallbackName]
        if type(callback) == "function" then
            EventManager.Remove(nEventId, self, callback)
        end
    end
    if self.BossId then
        EventManager.RemoveEntityEvent("HpChanged", self.BossId, self, self.OnEvent_HpChanged)
        EventManager.RemoveEntityEvent("BossRushMonsterLevelChanged", self.BossId, self, self.OnEvent_BossRushMonsterLevelChanged)
        EventManager.RemoveEntityEvent("BossRushMonsterBattleAttrChanged", self.BossId, self, self.OnEvent_BossRushMonsterBattleAttrChanged)
        self.BossId = nil
    end
end
return ScoreBossEditor