---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wqc.
--- DateTime: 2023/6/29 14:12
---

local BattleTestComboClipEditor = class("BattleTestComboClipEditor")


local RapidJson = require "rapidjson"




local Actor2DManager = require "Game.Actor2D.Actor2DManager"

local mapEventConfig = {
    --LevelStateChanged = "OnEvent_SendMsgFinishBattle",
    --[EventId.AbandonBattle] = "OnEvent_AbandonBattle",
    --InteractiveBoxGet = "OnEvent_OpenChest",
    LoadLevelRefresh = "OnEvent_LoadLevelRefresh",
    AdventureModuleEnter = "OnEvent_AdventureModuleEnter",
    TestBedNoteChange = "OnEvent_TestBedNoteChange",
}
local tbTheme = {1,2,3,4}
function BattleTestComboClipEditor:Init(parent,nSelectId,nTeamIdx,tbChestS,tbChestL,tbDisc)
    self.bSettle = false
    self.parent = parent
    self:BindEvent()
    self._nSelectId = nSelectId
    self.nCurTeamIndex = nTeamIdx
    self.tbChar = PlayerData.Team:GetTeamCharId(nTeamIdx)
    self.nLargeTotalCount = 0
    self.nSmallTotalCount = 0
    self.curSmallCount = 0
    self.curLargeCount = 0
    self.bNewSmall = false
    self.bNewLarge = false
    self._tbBoxS = {}
    self._tbBoxL = {}
    self._tbOpendChestS = {} -- 在主线战斗中开启的宝箱索引
    self._tbOpendChestL = {} -- 在主线战斗中开启的宝箱索引
    local mapMainline = ConfigTable.GetData_Mainline(nSelectId)
    self:PrePorcessChestData(self._nSelectId)
    self.nSmallTotalCount = #self._tbBoxS
    self.nLargeTotalCount = #self._tbBoxL
    self.tbDisc = tbDisc

    CS.AdventureModuleHelper.EnterBattleTestComboClipMap(mapMainline.FloorId, self.tbChar,tbChestS,tbChestL)
    self.curSmallCount = #tbChestS
    self.curLargeCount = #tbChestL
    NovaAPI.EnterModule("AdventureModuleScene", true)
end
function BattleTestComboClipEditor:InitBootConfig(parent,nSelectId,tbTeam,tbChestS,tbChestL, tbTalentSkillAI,tbDisc,tbNote, tbSkinId)
    self.parent = parent
    self:BindEvent()
    self._nSelectId = 10101
    self.nCurTeamIndex = 0
    self.tbChar = tbTeam
    self.nLargeTotalCount = 0
    self.nSmallTotalCount = 0
    self.curSmallCount = 0
    self.curLargeCount = 0
    self.bNewSmall = false
    self.bNewLarge = false
    self._tbBoxS = {}
    self._tbBoxL = {}
    self._tbOpendChestS = {} -- 在主线战斗中开启的宝箱索引
    self._tbOpendChestL = {} -- 在主线战斗中开启的宝箱索引
    self.tbTalentSkillAI = tbTalentSkillAI
    self:PrePorcessChestData(self._nSelectId)
    self.nSmallTotalCount = #self._tbBoxS
    self.nLargeTotalCount = #self._tbBoxL
    self.tbDisc = tbDisc
    self.tbNote = tbNote
    self.tbSkinId = tbSkinId

    for idx, nCharId in ipairs(self.tbChar) do
        local stActorInfo,nHeartStoneLevel= self:CalCharFixedEffect(nCharId,idx == 1)
        safe_call_cs_func(CS.AdventureModuleHelper.SetActorAttribute,nCharId,stActorInfo)
    end
    self:SetTheme()
    CS.AdventureModuleHelper.EnterBattleTestComboClipMap(nSelectId, tbTeam,tbChestS,tbChestL)
    NovaAPI.EnterModule("AdventureModuleScene", true)
end
function BattleTestComboClipEditor:SetTheme()
    --safe_call_cs_func(CS.AdventureModuleHelper.SetRglTheme,self.tbTheme)
end
function BattleTestComboClipEditor:BindEvent()
    if type(mapEventConfig) ~= "table" then
        return
    end
    for nEventId, sCallbackName in pairs(mapEventConfig) do
        local callback = self[sCallbackName]
        if type(callback) == "function" then
            EventManager.Add(nEventId, self, callback)
        end
    end
end
function BattleTestComboClipEditor:UnBindEvent()
    if type(mapEventConfig) ~= "table" then
        return
    end
    for nEventId, sCallbackName in pairs(mapEventConfig) do
        local callback = self[sCallbackName]
        if type(callback) == "function" then
            EventManager.Remove(nEventId, self, callback)
        end
    end
end
function BattleTestComboClipEditor:CalCharFixedEffect(nCharId,bMainChar)
    local stActorInfo = CS.Lua2CSharpInfo_CharAttribute()
    local nHeartStoneLevel = PlayerData.Char:CalCharacterAttrBattle(nCharId,stActorInfo,bMainChar,self.tbDisc)
    if self.tbSkinId and self.tbSkinId[nCharId] then
        stActorInfo.skinId = self.tbSkinId[nCharId]
    end
    return stActorInfo,nHeartStoneLevel
end
function BattleTestComboClipEditor:PrePorcessChestData(nMainlineId) --预处理DataTable的宝箱数�?
    if ConfigTable.GetData_Mainline(nMainlineId) == nil then
        printError("no level data�?"..nMainlineId)
        return
    end
    local tbChestS = decodeJson(ConfigTable.GetData_Mainline(nMainlineId).MinChestReward)
    local tbChestL = decodeJson(ConfigTable.GetData_Mainline(nMainlineId).MaxChestReward)
    self._tbBoxS = tbChestS
    self._tbBoxL = tbChestL
end


function BattleTestComboClipEditor:OnEvent_LoadLevelRefresh()
    self:ChangeNote()
    self:ResetNoteInfo()
    local wait = function()
        --printError("2222222")
        coroutine.yield(CS.UnityEngine.WaitForEndOfFrame())
        coroutine.yield(CS.UnityEngine.WaitForEndOfFrame())
        coroutine.yield(CS.UnityEngine.WaitForEndOfFrame())
        --EventManager.Hit(EventId.ClosePanel,PanelId.Adventure)
        --NovaAPI.InputDisable()
        --printError("333333")skill_btn_dodge_bg
        GameObject.Find("==== UI ROOT ====/---- UI ----/BattleDashboard").gameObject:SetActive(false)
        GameObject.Find("==== UI ROOT ====/---- UI ----/MainBattleMenu").gameObject:SetActive(false)
        local path = "Assets/AssetBundles/UI/_testBed/TestBedUI.prefab";

        local uiP = CS.UnityEditor.AssetDatabase.LoadAssetAtPath(path, typeof(Object))
        local tPa =  GameObject.Find("==== UI ROOT ====/---- UI ----").transform
        instantiate(uiP, tPa)
    end
    cs_coroutine.start(wait)
end

function BattleTestComboClipEditor:OnEvent_AdventureModuleEnter()
    print("OnEvent_AdventureModuleEnter")
    for idx, nCharId in ipairs(self.tbChar) do
        local stActorInfo,nHeartStoneLevel= self:CalCharFixedEffect(nCharId,idx== 1)
        safe_call_cs_func(CS.AdventureModuleHelper.SetActorAttribute,nCharId,stActorInfo)
    end
    self:SetTheme()
    self:ResetDiscInfo()
    self:ResetNoteInfo()
    EventManager.Hit(EventId.OpenPanel, PanelId.Adventure,self.tbChar)
end

function BattleTestComboClipEditor:ResetDiscInfo()
    local tbDiscInfo = {}
    for k, nDiscId in ipairs(self.tbDisc) do
        if k <= 3 then
            local mapDiscData = PlayerData.Disc:GetDiscById(nDiscId)
            if mapDiscData and mapDiscData.sName then
                local discInfo = mapDiscData:GetDiscInfo(self.tbNote)
                table.insert(tbDiscInfo, discInfo)
            else
                printError("星盘数据有误id:" .. nDiscId)
            end
        end
    end
    safe_call_cs_func(CS.AdventureModuleHelper.SetDiscInfo,tbDiscInfo)
end

function BattleTestComboClipEditor:ResetNoteInfo()
    local tbNoteInfo = {}
    for i, v in pairs(self.tbNote) do
        local noteInfo = CS.Lua2CSharpInfo_NoteInfo()
        noteInfo.noteId = i
        noteInfo.noteCount = v
        table.insert(tbNoteInfo, noteInfo)
    end
    safe_call_cs_func(CS.AdventureModuleHelper.SetNoteInfo, tbNoteInfo)
end

function BattleTestComboClipEditor:ChangeNote()
    if not self.mapDiscEft then
        self.mapDiscEft = {}
    end
    for k, nDiscId in ipairs(self.tbDisc) do
        if k <= 3 then
            local mapDiscData = PlayerData.Disc:GetDiscById(nDiscId)
            if mapDiscData and mapDiscData.sName then
                if self.mapDiscEft[nDiscId] == nil then
                    self.mapDiscEft[nDiscId] = {}
                else
                    --移除老效果
                    for _, tbEft in pairs(self.mapDiscEft[nDiscId]) do
                        for _, tbEftData in ipairs(tbEft) do
                            UTILS.RemoveEffect(tbEftData[1],tbEftData[2])
                        end
                    end
                    self.mapDiscEft[nDiscId] = {}
                end
                --添加新效果
                local tbDiscEft = mapDiscData:GetSkillEffect(self.tbNote)
                for _, mapEft in ipairs(tbDiscEft) do
                    if self.mapDiscEft[nDiscId][mapEft[1]] == nil then
                        self.mapDiscEft[nDiscId][mapEft[1]] = {}
                        for _, nCharId in ipairs(self.tbChar) do
                            local nEftUid = UTILS.AddEffect(nCharId,mapEft[1],mapEft[2],0)
                            table.insert(self.mapDiscEft[nDiscId][mapEft[1]],{nEftUid,nCharId})
                        end
                    end
                end
            else
                printError("星盘数据有误id:" .. nDiscId)
            end
        end
    end
end

function BattleTestComboClipEditor:OnEvent_TestBedNoteChange(noteList)
    if noteList then
        self.tbNote = {}
        for i = 0, noteList.Count - 1 do
            self.tbNote[noteList[i].Id] = noteList[i].count
        end
        self:ResetNoteInfo()
        self:ResetDiscInfo()
        self:ChangeNote()
    end
end
return BattleTestComboClipEditor