---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wqc.
--- DateTime: 2024/12/11 9:58
---

local PlayerVideoData = class("PlayerVideoData")

function PlayerVideoData:Init()
    self.isShowJump = false

    EventManager.Add("Play_AvPro_Video", self, self.PlayAvProVideo)
    EventManager.Add("Close_AvPro_Video", self, self.CloseAvProVideo)
    EventManager.Add("Video_Resources_LostTip", self, self.VideoResourcesLostTip)
end

function PlayerVideoData:UnInit()
    EventManager.Remove("Play_AvPro_Video", self, self.PlayAvProVideo)
    EventManager.Remove("Close_AvPro_Video", self, self.CloseAvProVideo)
    EventManager.Remove("Video_Resources_LostTip", self, self.VideoResourcesLostTip)
end

function PlayerVideoData:OpenJumpVideoPanel()
    self:SetIsShowJump(true)
    EventManager.Hit(EventId.OpenPanel,PanelId.ProVideoGUI)
end

function PlayerVideoData:CloseJumpVideoPanel()
    if self.isShowJump then
        self:SetIsShowJump(false)
        EventManager.Hit(EventId.ClosePanel,PanelId.ProVideoGUI)
    end
end

function PlayerVideoData:PlayAvProVideo()
    EventManager.Hit(EventId.OpenPanel,PanelId.ProVideoGUI)
end

function PlayerVideoData:CloseAvProVideo()
    EventManager.Hit(EventId.ClosePanel,PanelId.ProVideoGUI)
end

function PlayerVideoData:SetIsShowJump(isShow)
    self.isShowJump = isShow
end

function PlayerVideoData:VideoResourcesLostTip()
    local strTips = ConfigTable.GetUIText("Lost_Resources_Tips")
    EventManager.Hit(EventId.OpenMessageBox, strTips)
end

return PlayerVideoData