---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wqc.
--- DateTime: 2025/3/13 16:12
---Boss积分挑战

local PlayerScoreBossData = class("PlayerScoreBossData")
local LocalData = require "GameCore.Data.LocalData"
function PlayerScoreBossData:Init()
    self.BattleLv = 0
    self:InitBaseData()
    self.isGetScInfo = false

    EventManager.Add(EventId.IsNewDay, self, self.OnEvent_NewDay)
    self:InitTableData()
    self:InitRankData()
end

function PlayerScoreBossData:InitTableData()

    self.tabScoreNeed = {}
    local function foreach_Base(baseData)
        self.tabScoreNeed[baseData.Star] = baseData.ScoreNeed
    end
    ForEachTableLine(DataTable.ScoreBossStar,foreach_Base)

    self.maxStarNeed = 0
    self.tabScoreBossReward = {}
    local function foreach_Base(baseData)
        self.tabScoreBossReward[baseData.Id] = baseData
        if self.maxStarNeed < baseData.StarNeed then
            self.maxStarNeed = baseData.StarNeed
        end
    end
    ForEachTableLine(DataTable.ScoreBossReward,foreach_Base)

    self.maxRankCount = 0
    local function foreach_Base(baseData)
        self.maxRankCount = self.maxRankCount + 1
    end
    ForEachTableLine(DataTable.ScoreBossRank,foreach_Base)
end

function PlayerScoreBossData:UnInit()
    --EventManager.Remove("Get_Player_Data_Succeed",self,self.GetScoreBossInstanceData)
    EventManager.Remove(EventId.IsNewDay, self, self.OnEvent_NewDay)
end

function PlayerScoreBossData:InitBaseData()
    self.ControlId = 0 --周期 id
    self.Score = 0 --当前分数
    self.Star = 0 --当前星级
    self.tabStarRewards = {} --已领取的星级奖励
    self.tabScoreBossLevel = {} -- 每个关卡的公关记录

    --表格数据
    self.OpenLevelGroup = {}
    self.StartTime = 0 -- 关卡开始时间
    self.EndTime = 0 -- 关卡结束时间

    self.tabCachedBuildId = {}
end

function PlayerScoreBossData:GetInitInfoState()
    --local nCurTime = CS.ClientManager.Instance.serverTimeStamp
    --if self.EndTime ~= 0 and nCurTime > self.EndTime then
    --    self.isGetScInfo = false
    --end
    if self.ControlId ~= 0 then
        local nCurTime = CS.ClientManager.Instance.serverTimeStamp
        local tmpControl = ConfigTable.GetData("ScoreBossControl", self.ControlId + 1)
        if tmpControl then
            local startTime = CS.ClientManager.Instance:ISO8601StrToTimeStamp(tmpControl.StartTime)
            if nCurTime >= startTime then
                self.isGetScInfo = false
            end
        end
    end
    return self.isGetScInfo
end
--获取关卡数据
function PlayerScoreBossData:GetScoreBossInstanceData(openPanelCallBack)
    local function msgCallback(_, mapMsgData)
        self:CacheScoreBossInstanceData(mapMsgData,openPanelCallBack)
    end
    HttpNetHandler.SendMsg(NetMsgId.Id.score_boss_info_req, {}, nil, msgCallback)
end
function PlayerScoreBossData:CacheScoreBossInstanceData(mapMsgData,openPanelCallBack)
    self:InitBaseData()
    if mapMsgData == nil or mapMsgData.ControlId == 0 then
        EventManager.Hit(EventId.OpenMessageBox, ConfigTable.GetUIText("ScoreBoss_Season_Error"))
        return
    end

    --缓存关卡数据
    self.ControlId = mapMsgData.ControlId
    self.Score = mapMsgData.Score
    self.Star = mapMsgData.Star
    for i, v in pairs(mapMsgData.StarRewards) do
        table.insert(self.tabStarRewards,v)
    end

    --处理关卡表格数据
    local scoreBossControl = ConfigTable.GetData("ScoreBossControl", self.ControlId)
    if scoreBossControl ~= nil then
        local levelGroup = scoreBossControl.LevelGroup
        if #levelGroup > 0 then
            for i = 1, #levelGroup do
                table.insert(self.OpenLevelGroup,levelGroup[i])
                local tab = {}
                tab.LevelId = levelGroup[i] --关卡 id
                tab.BuildId = 0 --build id
                tab.Score = 0 --保存的分数
                tab.Star = 0 --保存的星级
                tab.SkillScore = 0 --技巧得分
                self.tabScoreBossLevel[levelGroup[i]] = tab
            end
        end
        self.StartTime = CS.ClientManager.Instance:ISO8601StrToTimeStamp(scoreBossControl.StartTime)
        self.EndTime = CS.ClientManager.Instance:ISO8601StrToTimeStamp(scoreBossControl.EndTime) - ConfigTable.GetConfigNumber("SeasonEndThreshold")
    end

    for i, v in pairs(mapMsgData.Levels) do
        if self.tabScoreBossLevel[v.LevelId] then
            self.tabScoreBossLevel[v.LevelId].BuildId = v.BuildId --build id
            self.tabScoreBossLevel[v.LevelId].Score = v.Score --保存的分数
            self.tabScoreBossLevel[v.LevelId].Star = v.Star --保存的星级
            self.tabScoreBossLevel[v.LevelId].SkillScore = v.SkillScore --保存的星级
        else
            printError("ScoreBossControl 下发数据和配置数据对不上")
        end
    end
    if not self.isGetScInfo then
        EventManager.Hit("Get_ScoreBoss_InfoReq")
    end
    self.isGetScInfo = true
    self:RefreshRedMsg()
    if openPanelCallBack then
        openPanelCallBack()
    end
end

function PlayerScoreBossData:RefreshRedMsg()
    self.isHave = false
    for i, v in ipairs(self.tabScoreBossReward) do
        if self.Star >= v.StarNeed and table.indexof(self.tabStarRewards,v.StarNeed) == 0 then
            self.isHave = true
            break
        end
    end
    RedDotManager.SetValid(RedDotDefine.Map_ScoreBossStar, nil, self.isHave)
end

function PlayerScoreBossData:UpdateRedDot(mapMsgData)
    if nil == mapMsgData then
        return
    end

    RedDotManager.SetValid(RedDotDefine.Map_ScoreBossStar, nil, mapMsgData.New)
end

function PlayerScoreBossData:ChangeTabScoreBossLevel(nLevelId,nBuildId,nScore,nStar,nBehaviorScore,isReplace,tabOtherLevelId)

    if isReplace then
        self.tabScoreBossLevel[nLevelId].BuildId = nBuildId
        self.tabScoreBossLevel[nLevelId].Score = nScore
        self.tabScoreBossLevel[nLevelId].Star = nStar
        self.tabScoreBossLevel[nLevelId].SkillScore = nBehaviorScore
    else
        if nScore >= self.tabScoreBossLevel[nLevelId].Score then
            self.tabScoreBossLevel[nLevelId].BuildId = nBuildId
            self.tabScoreBossLevel[nLevelId].Score = nScore
            self.tabScoreBossLevel[nLevelId].Star = nStar
            self.tabScoreBossLevel[nLevelId].SkillScore = nBehaviorScore
        end
    end

    if #tabOtherLevelId > 0 then
        for i, v in pairs(tabOtherLevelId) do
            local tmpLevelId = v
            self.tabScoreBossLevel[tmpLevelId].BuildId = 0
            self.tabScoreBossLevel[tmpLevelId].Score = 0
            self.tabScoreBossLevel[tmpLevelId].Star = 0
            self.tabScoreBossLevel[tmpLevelId].SkillScore = 0
        end
    end

    local _totalStar = 0
    local _totalScore = 0
    for i, v in pairs(self.tabScoreBossLevel) do
        _totalStar = _totalStar + v.Star
        _totalScore = _totalScore + v.Score
    end

    self.Score = _totalScore
    self.Star = _totalStar

    self:RefreshRedMsg()
end

function PlayerScoreBossData:OnEvent_NewDay()
    --判断新的一天 当前时间是否大于结束时间，大于则请求新的关卡数据
    local nCurTime = CS.ClientManager.Instance.serverTimeStamp
    if self.EndTime ~= 0 and nCurTime > self.EndTime then
        self:GetScoreBossInstanceData(nil)
        self:SendScoreBossApplyReq(function() end)
    end
end

function PlayerScoreBossData:SendEnterScoreBossApplyReq(nLevelId,nBuildId)

    local msg = {}
    msg.LevelId = nLevelId
    msg.BuildId = nBuildId
    local function msgCallback()
        self.CurHPLvScore = 0 --当前血条等分
        self.HPLvScore = 0   --上一血条累计等分
        self.CurHPDamage = 0 --当前血条消耗血量
        self.BehaviorScore = 0
        self.BehaviorScoreCount = 0

        local curTimeStamp = CS.ClientManager.Instance.serverTimeStampWithTimeZone
        local sKey = LocalData.GetPlayerLocalData("ScoreBossRecordKey")
        if sKey ~= nil and sKey ~= "" then
            NovaAPI.DeleteRecFile(sKey)
        end
        sKey = tostring(curTimeStamp)
        LocalData.SetPlayerLocalData("ScoreBossRecordKey", sKey)
        self:EnterScoreBossInstance(nLevelId,nBuildId)
    end
    HttpNetHandler.SendMsg(NetMsgId.Id.score_boss_apply_req, msg, nil, msgCallback)
end

--进入关卡
function PlayerScoreBossData:EnterScoreBossInstance(nLevelId, nBuildId)
    if self.curLevel ~= nil then
        printError("当前关卡level不为空1")
        return
    end
    self._EntryTime = CS.ClientManager.Instance.serverTimeStampWithTimeZone
    self.entryLevelId = nLevelId
    self.entryBuild = nBuildId
    local luaClass =  require "Game.Adventure.ScoreBoss.ScoreBossLevel"
    if luaClass == nil then
        return
    end
    self.curLevel = luaClass
    if type(self.curLevel.BindEvent) == "function" then
        self.curLevel:BindEvent()
    end
    if type(self.curLevel.Init) == "function" then
        self.curLevel:Init(self,nLevelId,nBuildId)
    end
end

function PlayerScoreBossData:EnterScoreBossInstanceEditor(nLevelId,tbChar, tbDisc, tbNote)
    if self.curLevel ~= nil then
        printError("当前关卡level不为空1")
        return
    end
    self.entryLevelId = nLevelId
    self.CurHPLvScore = 0 --当前血条等分
    self.HPLvScore = 0   --上一血条累计等分
    self.CurHPDamage = 0 --当前血条消耗血量
    self.BehaviorScore = 0
    self.BehaviorScoreCount = 0
    local luaClass =  require "Game.Adventure.ScoreBoss.ScoreBossEditor"
    if luaClass == nil then
        return
    end
    self.curLevel = luaClass
    if type(self.curLevel.BindEvent) == "function" then
        self.curLevel:BindEvent()
    end
    if type(self.curLevel.Init) == "function" then
        self.curLevel:Init(self,nLevelId,tbChar, tbDisc, tbNote)
    end
end

function PlayerScoreBossData:LevelEnd()
    if nil ~= self.curLevel and type(self.curLevel.UnBindEvent) == "function" then
        self.curLevel:UnBindEvent()
    end
    self.curLevel = nil
end
------- 进入关卡 ------
--缓存进入关卡小队id
function PlayerScoreBossData:CacheBuildCharTid(tab)
    self.entryLevelChar = tab
end

function PlayerScoreBossData:GetEntryBuildCharTid()
    return self.entryLevelChar
end

function PlayerScoreBossData:SetSelBuildId(nBuildId,levelId)
    self.tabCachedBuildId[levelId] = nBuildId
end

--获取关卡BuildId
function PlayerScoreBossData:GetCachedBuild(levelId)
    return self.tabCachedBuildId[levelId] or 0
end

--获取关卡BuildId
function PlayerScoreBossData:GetLevelBuild(levelId)
    if self.tabScoreBossLevel[levelId] and self.tabScoreBossLevel[levelId].BuildId ~= 0 then
        return self.tabScoreBossLevel[levelId].BuildId
    end
    return 0
end

function PlayerScoreBossData:GetLevelData(levelId)
    if self.tabScoreBossLevel[levelId] then
        return self.tabScoreBossLevel[levelId]
    end
    return nil
end

--获得build char
function PlayerScoreBossData:GetBuildChar(buildId,callBack)
    local function GetDataCallback(tbBuildData,mapAllBuild)
        local mapBuild = mapAllBuild[buildId]
        local tbCharId = {}
        if mapBuild ~= nil then
            for _,mapChar in ipairs(mapBuild.tbChar) do
                table.insert(tbCharId,mapChar.nTid)
            end
        end
        callBack(tbCharId)
    end
    PlayerData.Build:GetAllBuildBriefData(GetDataCallback)
end

--结算判断是否有相同的 角色在另外一组
function PlayerScoreBossData:JudgeOtherLevelHaveSameChar(entryLevelId,entryBuildId,callBack)
    local otherLevelId = { }
    local function GetDataCallback(tbBuildData,mapAllBuild)
        local entryBuild = mapAllBuild[entryBuildId]
        local entryChar = {}
        for _,mapChar in ipairs(entryBuild.tbChar) do
            table.insert(entryChar,mapChar.nTid)
        end
        for i, v in pairs(self.OpenLevelGroup) do
            if v ~= entryLevelId then
                if self.tabScoreBossLevel[v] and self.tabScoreBossLevel[v].BuildId ~= 0 then
                    local mapBuild = mapAllBuild[self.tabScoreBossLevel[v].BuildId]
                    if mapBuild ~= nil then
                        local tbCharId = {}
                        for _,mapChar in ipairs(mapBuild.tbChar) do
                            table.insert(tbCharId,mapChar.nTid)
                        end

                        for i1, v1 in pairs(tbCharId) do
                            local idx = table.indexof(entryChar, v1)
                            if idx ~= 0 then
                                table.insert(otherLevelId,self.tabScoreBossLevel[v].LevelId)
                                break
                            end
                        end
                    end
                end
            end
        end
        --otherLevelId ~= 0 则有相同
        callBack(otherLevelId)
    end
    PlayerData.Build:GetAllBuildBriefData(GetDataCallback)
end

--结算时判断当前关卡是否已有其他build或者角色不同
function PlayerScoreBossData:JudgeLevelCacheOtherChar(entryLevelId,entryBuildId,callBack)
    local tmpBuild = self:GetLevelBuild(entryLevelId)
    if tmpBuild == 0 or tmpBuild == entryBuildId then
        callBack(false)
        return
    end

    local function GetDataCallback(tbBuildData,mapAllBuild)
        local cacheBuild = mapAllBuild[tmpBuild]
        if cacheBuild == nil then
            callBack(false)
            return
        end
        local cacheChar = {}
        for _,mapChar in ipairs(cacheBuild.tbChar) do
            table.insert(cacheChar,mapChar.nTid)
        end

        for i, v in pairs(cacheChar) do
            local idx = table.indexof(self.entryLevelChar,v)
            if idx == 0 then
                callBack(true)
                return
            end
        end
        callBack(false)
    end
    PlayerData.Build:GetAllBuildBriefData(GetDataCallback)
end

--伤害转换为分数
function PlayerScoreBossData:DamageToScore(damageValue,SwitchRate,battleLv)
    self.CurHPDamage = damageValue
    self.CurHPLvScore = math.floor(damageValue/SwitchRate)
    self.BattleLv = battleLv
    --printError("DamageToScore === " .. self.CurHPLvScore .. "   " .. self.CurHPDamage .. "  " .. SwitchRate .. "  " .. maxHp)
    EventManager.Hit("ScoreBoss_Score_Change")
end

--
function PlayerScoreBossData:HPLevelChanged()
    --printError("HPLevelChanged ********** === " .. self.HPLvScore .. "   " .. self.CurHPLvScore)
    self.HPLvScore = self.HPLvScore + self.CurHPLvScore
    self.CurHPLvScore = 0
    self.CurHPDamage = 0
    EventManager.Hit("ScoreBoss_Score_Change")
end

function PlayerScoreBossData:BehaviorToScore(nScore)
    self.BehaviorScore = nScore
    self.BehaviorScoreCount = self.BehaviorScoreCount + 1
    EventManager.Hit("ScoreBoss_Score_Change")
    EventManager.Hit("ScoreBoss_Score_SkillChange")
end

function PlayerScoreBossData:GetTotalScore()
    local totalScore = self.HPLvScore + self.CurHPLvScore + self.BehaviorScore
    return totalScore
end

function PlayerScoreBossData:GetBehaviorScore()
    return self.BehaviorScore,self.BehaviorScoreCount
end

function PlayerScoreBossData:GetDamageScore()
    return self.HPLvScore + self.CurHPLvScore
end

function PlayerScoreBossData:ScoreToStar()
    local tmpStar = 0
    local totalScore = self.HPLvScore + self.CurHPLvScore + self.BehaviorScore
    for i, v in pairs(self.tabScoreNeed) do
        if v <= totalScore and tmpStar < i then
            tmpStar = i
        end
    end
    return tmpStar
    --总分数 星数
end

function PlayerScoreBossData:QuiteLevel()
    self:LevelEnd()
    CS.AdventureModuleHelper.ResumeLogic()
    local function levelEndCallback()
        EventManager.Remove("ADVENTURE_LEVEL_UNLOAD_COMPLETE",self,levelEndCallback)
        NovaAPI.EnterModule("MainMenuModuleScene", true)
    end
    EventManager.Add("ADVENTURE_LEVEL_UNLOAD_COMPLETE",self,levelEndCallback)
    CS.AdventureModuleHelper.LevelStateChanged(true,0,true)
end

function PlayerScoreBossData:SureScoreBossSettleReq(totalStar,totalScore,isReplace,tabOtherLevelId)
    NovaAPI.StopRecord()
    local tbSamples = UTILS.GetBattleSamples()
    local sKey = LocalData.GetPlayerLocalData("ScoreBossRecordKey")
    local bSuccess, nCheckSum = NovaAPI.GetRecorderKey(sKey)
    local tbSendSample = {
        Sample = tbSamples,
        Checksum = nCheckSum,
    }

    local msg = {}
    msg.Star = totalStar
    msg.Score = totalScore
    msg.sample = tbSendSample
    msg.DamageScore = math.floor(self.HPLvScore + self.CurHPLvScore)
    msg.SkillScore = self.BehaviorScore
    msg.BossResultLevel = self.BattleLv
    msg.Events = {List = PlayerData.Achievement:GetBattleAchievement(GameEnum.levelType.ScoreBoss,true)}

    local function msgCallback(_, mapMsgData)
        local oldRank = mapMsgData.oldRank
        local newRank = mapMsgData.newRank
        self:UploadRecordFile(mapMsgData.token)
        self:ChangeTabScoreBossLevel(self.entryLevelId,self.entryBuild,totalScore,totalStar,self.BehaviorScore,isReplace,tabOtherLevelId)
        CS.AdventureModuleHelper.ResumeLogic()
        EventManager.Hit("ScoreBossSettleSuccess",self.entryLevelId,totalScore,totalStar)
        self:LevelEnd()

        ------埋点数据------
        self._EndTime = CS.ClientManager.Instance.serverTimeStampWithTimeZone
        local leveData = ConfigTable.GetData("ScoreBossLevel", self.entryLevelId)
        local tabUpLevel = {}
        table.insert(tabUpLevel,{"role_id",tostring(PlayerData.Base._nPlayerId)})
        table.insert(tabUpLevel,{"game_cost_time",tostring(self.TotalTime)})
        table.insert(tabUpLevel,{"real_cost_time",tostring(self._EndTime - self._EntryTime)})
        table.insert(tabUpLevel,{"build_id",tostring(self.entryBuild)})
        table.insert(tabUpLevel,{"battle_id",tostring(leveData.MonsterId)})
        table.insert(tabUpLevel,{"total_score",tostring(totalScore)})
        table.insert(tabUpLevel,{"boss_result_level",tostring(self.BattleLv)})
        NovaAPI.UserEventUpload("boss_rush",tabUpLevel)
        ------埋点数据------

        self.isLevelClear = true
    end
    HttpNetHandler.SendMsg(NetMsgId.Id.score_boss_settle_req, msg, nil, msgCallback)
end

function PlayerScoreBossData:UploadRecordFile(sToken)
    local sKey = LocalData.GetPlayerLocalData("ScoreBossRecordKey") or ""
    if sKey ~= nil and sKey ~= "" then
        if sToken ~= nil and sToken ~= "" then
            NovaAPI.UploadStartowerFile(sToken, sKey)
        else
            NovaAPI.DeleteRecFile(sKey)
        end
    end
    LocalData.SetPlayerLocalData("ScoreBossRecordKey", "")
end

function PlayerScoreBossData:SendScoreBossSettleReq(totalTime)
    self.TotalTime = totalTime
    CS.AdventureModuleHelper.PauseLogic()
    local function JudgeOther(otherLevelId)
        local totalScore = self.HPLvScore + self.CurHPLvScore + self.BehaviorScore
        local totalStar = self:ScoreToStar()

        if #otherLevelId == 0 then
            --队伍中三人没有出现在其他队伍中
            --判断进入队伍三个角色 和已保存的是否一至（先判断buildId,再判断角色）,不一致则显示替换，一致直接结算
            local function judgeCache(isReplace)
                if isReplace then
                    --需要替换确认
                    local function ConfirmCb()
                        self:SureScoreBossSettleReq(totalStar,totalScore,true, {})
                    end
                    local function CancelCb()
                       self:QuiteLevel()
                    end
                    EventManager.Hit(EventId.OpenPanel,PanelId.ScoreBossReplaceBD,self.entryLevelId,ConfirmCb,CancelCb)
                else
                    --不需要替换
                    self:SureScoreBossSettleReq(totalStar,totalScore,false, {})
                end
            end
            --判断当前组是否需要替换build
            self:JudgeLevelCacheOtherChar(self.entryLevelId,self.entryBuild,judgeCache)

        else
            --队伍中三人出现在其他队伍中
            --判断进入队伍三个角色 和已保存的是否一至（先判断buildId,再判断角色）,不一致则显示替换，一致再次弹出清除另一组信息
            --二次确认界面
            local function judgeCache(isReplace)
                if isReplace then
                    --需要替换确认 并且要清空其他组
                    local function ConfirmCb()
                        local function ConfirmClearCb()
                            self:SureScoreBossSettleReq(totalStar,totalScore,true, otherLevelId)
                        end
                        local function CancelClearCb()
                            self:QuiteLevel()
                        end
                        EventManager.Hit(EventId.OpenPanel,PanelId.ScoreBossClearBD,otherLevelId,ConfirmClearCb,CancelClearCb)
                    end
                    --不需要替换 直接退出
                    local function CancelCb()
                        self:QuiteLevel()
                    end
                    EventManager.Hit(EventId.OpenPanel,PanelId.ScoreBossReplaceBD,self.entryLevelId,ConfirmCb,CancelCb)
                else
                    --不需要替换，再次确认是否清空其他组
                    local function ConfirmClearCb()
                        self:SureScoreBossSettleReq(totalStar,totalScore,true, otherLevelId)
                    end
                    local function CancelClearCb()
                        self:QuiteLevel()
                    end
                    EventManager.Hit(EventId.OpenPanel,PanelId.ScoreBossClearBD,otherLevelId,ConfirmClearCb,CancelClearCb)
                end
            end
            --判断当前组是否需要替换build
            self:JudgeLevelCacheOtherChar(self.entryLevelId,self.entryBuild,judgeCache)
        end
    end
    --判断其他关卡是否有相同角色
    self:JudgeOtherLevelHaveSameChar(self.entryLevelId,self.entryBuild,JudgeOther)
end

function PlayerScoreBossData:SendScoreBossStarRewardReceiveReq(cb,star)
    -- star星级 表格里（StarNeed）, 0 表示全部领取
    local msg = {}
    msg.Star = star
    local function msgCallback(_, mapMsgData)
        if star ~= 0 then
            table.insert(self.tabStarRewards ,star)
        else
            self.tabStarRewards = {}
            for i, v in pairs(self.tabScoreBossReward) do
                if v.StarNeed <= self.Star then
                    table.insert(self.tabStarRewards,v.StarNeed)
                end
            end
        end
        --显示奖励
        HttpNetHandler.ProcChangeInfo(mapMsgData)
        local mapDecodedChangeInfo = UTILS.DecodeChangeInfo(mapMsgData)
        UTILS.OpenReceiveByDisplayItem(mapDecodedChangeInfo["proto.Res"], mapMsgData)
        cb()

        self:RefreshRedMsg()
    end
    HttpNetHandler.SendMsg(NetMsgId.Id.score_boss_star_reward_receive_req, msg, nil, msgCallback)
end

----排行榜相关----
function PlayerScoreBossData:SendScoreBossApplyReq(cb)
    self:InitRankData()
    local function msgCallback(_, mapMsgData)
        self:SetRankMsg(mapMsgData,cb)
    end
    HttpNetHandler.SendMsg(NetMsgId.Id.score_boss_rank_req, { }, nil, msgCallback)
end

function PlayerScoreBossData:InitRankData()
    self.RankLastRefreshTime = 0
    self.RankSelfMsg = nil
    self.RankPlayerMsg = {}
    self.RankBorder = {}
    self.nRankTotalCount = 0
end

function PlayerScoreBossData:SetRankMsg(mapMsgData,cb)
    self.RankLastRefreshTime = mapMsgData.LastRefreshTime
    if mapMsgData.Self then
        self.RankSelfMsg = mapMsgData.Self
    end
    if mapMsgData.Rank then
        for i, v in pairs(mapMsgData.Rank) do
            table.insert(self.RankPlayerMsg,v)
        end
    end
    if mapMsgData.Border then
        for i, v in pairs(mapMsgData.Border) do
            table.insert(self.RankBorder,v)
        end
    end
    
    if mapMsgData.Total then
        self.nRankTotalCount = mapMsgData.Total
    end
    
    cb()
end

function PlayerScoreBossData:CheckRankDataLastest()
    -- 自己没有数据的时候，没有自己的排名信息和总榜不匹配的问题，视作最新
    if self.RankSelfMsg == nil or self.RankSelfMsg.Rank == 0 then
        return true
    end
    
    local mapSelfDataInList = nil
    if self.RankSelfMsg.Rank <= #self.RankPlayerMsg then
        mapSelfDataInList = self.RankPlayerMsg[self.RankSelfMsg.Rank]
    else
        return false
    end
    -- 名次相同，昵称和分数相同，视作最新
    if mapSelfDataInList == nil or mapSelfDataInList.NickName ~= self.RankSelfMsg.NickName or mapSelfDataInList.Score ~= self.RankSelfMsg.Score then
        return false
    end
    return true
end

--获取自身排名信息
function PlayerScoreBossData:GetRankSelfMsg()
    return self.RankSelfMsg
end
--获取自身排名名次
function PlayerScoreBossData:GetSelfRankIndex()
    if self.RankSelfMsg then
        return self.RankSelfMsg.Rank
    end
    return 0
end
--获取排名分段分数
function PlayerScoreBossData:GetRankBorderCount(index)
    return self.RankBorder[index] or 0
end

--获取自身排名分段
function PlayerScoreBossData:GetSelfBorderIndex()
    for i, v in pairs(self.RankBorder) do
        if self.RankSelfMsg.Score >= v then
            return i
        end
    end
    return 1
end

--获取排行榜总人数
function PlayerScoreBossData:GetRankPlayerCount()
    return self.nRankTotalCount or 0
end
--获取排名信息数量
function PlayerScoreBossData:GetRankTableCount()
    return #self.RankPlayerMsg or 0
end
--获取排名信息
function PlayerScoreBossData:GetPlayerRankMsg(index)
    return self.RankPlayerMsg[index] or nil
end
----排行榜相关----


function PlayerScoreBossData:GetVoiceKey()
    local isFirst = false
    if not self.isFirstVoice then
        isFirst = true
        self.isFirstVoice = true
    end
    local timeNow = CS.ClientManager.Instance.serverTimeStamp
    local nHour = tonumber(os.date("%H", timeNow))
    if nHour >= 6 and nHour < 12 then
        return isFirst, "greetmorn_npc"
    elseif nHour >= 12 and nHour < 18 then
        return isFirst, "greetnoon_npc"
    else
        return isFirst, "greetnight_npc"
    end
end
return PlayerScoreBossData