---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wqc.
--- DateTime: 2025/1/15 14:25
---
local AVProVideoGUIPanel = class("AVProVideoGUIPanel", BasePanel)
AVProVideoGUIPanel._sSortingLayerName = AllEnum.SortingLayerName.UI_Top
AVProVideoGUIPanel._bIsMainPanel = false
AVProVideoGUIPanel._tbDefine = {
    {sPrefabPath = "AVProVideo/AVProVideoGUI.prefab", sCtrlName = "Game.UI.AVProVideo.AVProVideoGUICtrl"},
}

function AVProVideoGUIPanel:Awake()
end

function AVProVideoGUIPanel:OnEnable()
end

function AVProVideoGUIPanel:OnDisable()
end

function AVProVideoGUIPanel:OnDestroy()
end
return AVProVideoGUIPanel