---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wqc.
--- DateTime: 2023/11/27 16:25
---

local CampingJoystickPanel = class("CampingJoystickPanel", BasePanel)

--CampingJoystickPanel._bIsMainPanel = false

CampingJoystickPanel._tbDefine = {
    {sPrefabPath = "Campaing/CampingJoystick.prefab", sCtrlName = "Game.UI.Camping.CampingJoystickCtrl"},
}
-------------------- local function --------------------
-------------------- base function --------------------
function CampingJoystickPanel:Awake()
end
function CampingJoystickPanel:OnEnable()
end
function CampingJoystickPanel:OnDisable()
end
function CampingJoystickPanel:OnDestroy()
end
-------------------- callback function --------------------
return CampingJoystickPanel