---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wqc.
--- DateTime: 2025/3/14 11:18
---

local ScoreBossBattlePanel = class("ScoreBossBattlePanel", BasePanel)
local GamepadUIManager = require "GameCore.Module.GamepadUIManager"

ScoreBossBattlePanel.OpenMinMap = true
ScoreBossBattlePanel._bAddToBackHistory = false
ScoreBossBattlePanel._tbDefine =
{   -- 定义当前 Panel 由哪些 prefab 组成，以及每个 prefab 分别由哪个 ctrl 关联控制
    --{ sPrefabPath = "RoguelikeItemTip/RoguelikeItemTipPanel.prefab",        sCtrlName = "Game.UI.RoguelikeItemTips.RoguelikeItemTipsCtrl" },
    { sPrefabPath = "Battle/BattleDashboard.prefab",                        sCtrlName = "Game.UI.Battle.BattleDashboardCtrl" },
    { sPrefabPath = "Battle/MainBattleMenu.prefab",                         sCtrlName = "Game.UI.Battle.MainBattleMenuCtrl" },
    -- { sPrefabPath = "Battle/VirtualJoystickUI/VirtualJoystickUI.prefab",    sCtrlName = "Game.UI.Battle.VirtualJoystickCtrl" },
    { sPrefabPath = "Battle/AdventureMainUI/AdventureMainUI.prefab",        sCtrlName = "Game.UI.Battle.MainBattleCtrl" },
    { sPrefabPath = "Battle/AdventureMainUI/BattlePopupTips.prefab",        sCtrlName = "Game.UI.Battle.BattlePopupTipsCtrl" },
    { sPrefabPath = "Play_ScoreBoss/ScoreBossLevelInfo.prefab",        sCtrlName = "Game.UI.ScoreBoss.ScoreBossLevelInfoCtrl" },
    { sPrefabPath = "Battle/SkillHintIndicators.prefab",                    sCtrlName = "Game.UI.Battle.SkillHintIndicator.HintIndicators" },
    { sPrefabPath = "Play_ScoreBoss/ScoreBossPausePanel.prefab",                 sCtrlName = "Game.UI.ScoreBoss.ScoreBossPauseCtrl", },
    {
        sPrefabPath = "Battle/SubSkillDisplay.prefab",
        sCtrlName = "Game.UI.Battle.SubSkillDisplay.SubSkillDisplayCtrl"
    },
}
function ScoreBossBattlePanel:Awake()
    GamepadUIManager.EnterAdventure()
    GamepadUIManager.EnableGamepadUI("BattleMenu", {}) -- 菜单和AdventureMainUI ctrl在OnEnable的时候会添加节点
    self.BattleType = GameEnum.worldLevelType.ScoreBoss
end
function ScoreBossBattlePanel:OnEnable()
    local wait = function()
        coroutine.yield(CS.UnityEngine.WaitForEndOfFrame())
        EventManager.Hit(EventId.OpenPanel, PanelId.Hud)
        EventManager.Hit(EventId.ClosePanel, PanelId.MainlineFormation)
        EventManager.Hit(EventId.ClosePanel, PanelId.RegionBossFormation)
    end
    cs_coroutine.start(wait)
end
function ScoreBossBattlePanel:OnAfterEnter()
    EventManager.Hit(EventId.SubSkillDisplayInit,self._tbParam[1])
end

function ScoreBossBattlePanel:OnDisable()
    GamepadUIManager.DisableGamepadUI("BattleMenu")
    GamepadUIManager.QuitAdventure()
end

return ScoreBossBattlePanel