---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wqc.
--- DateTime: 2024/6/12 17:27
---
local MainlineFormationDiscPanel = class("MainlineFormationDiscPanel", BasePanel)

MainlineFormationDiscPanel._tbDefine = {
    {sPrefabPath = "MainlineFormationDisc/MainlineFormationDiscPanelEx.prefab", sCtrlName = "Game.UI.MainlineFormationDiscEx.MainlineFormationDiscCtrl"},
}

function MainlineFormationDiscPanel:Awake()
    self.curRoguelikeId = nil
    self.nTeamIndex = nil
    local tbParam = self:GetPanelParam()
    if type(tbParam) == "table" then
        self.curRoguelikeId = tbParam[1]
        self.nTeamIndex = tbParam[2]
        self.bSweep = tbParam[3]
    end
end

function MainlineFormationDiscPanel:OnEnable()
end

function MainlineFormationDiscPanel:OnDisable()
end

function MainlineFormationDiscPanel:OnDestroy()
end

return MainlineFormationDiscPanel